# Generated by Django 4.2.3 on 2023-07-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
